### PR TITLE
fix: copyToClipboard selection

### LINKED ISSUE #425: Some features not available in non-https mode (e.g. albyhub.local)
- crypto.subtle which is needed to decrypt the mnemonic locally in order to allow the user to do a key backup
- ~clipboard copy - I believe we should use a copy library that has a fallback or better support for this situation~

### PR DESCRIPTION
**Pull request by im-adithya**
Partially fixes #425

Fixes `copyToClipboard` not working in non-HTTPS mode

### CODE REVIEW

File: frontend/src/lib/clipboard.ts [hunk 1]
```diff
@@ -10,11 +10,21 @@ export function copyToClipboard(content: string) {
     textArea.style.position = "absolute";
     textArea.style.opacity = "0";
     document.body.appendChild(textArea);
-    textArea.select();
+    selectElement(textArea);
```
Comment (rolznz) [inline frontend/src/lib/clipboard.ts:13]: on the line below we don't await the promise, it could reject and we still would show the toast?

Comment (im-adithya) [reply frontend/src/lib/clipboard.ts]: Done!
