### PR TITLE
fix: hide alby extension banner if already installed

### LINKED ISSUE #347: "Install Alby Extension" button on wallet page is confusing if extensionis already installed

### PR DESCRIPTION
**Pull request by reneaaron**
Fixes #347

### CODE REVIEW

File: frontend/src/screens/wallet/index.tsx [hunk 1]
```diff
@@ -17,9 +18,18 @@ import {
...
+declare global {
+  interface Window { alby: any; }
+}
+
 function Wallet() {
   const { data: info } = useInfo();
   const { data: balances } = useBalances();
+  const [extensionInstalled, setExtensionInstalled] = useState(false);
+
+  useEffect(() => {
```
Comment (rolznz) [inline frontend/src/screens/wallet/index.tsx:30]: You need an effect, you can just do

`const extensionInstalled = window.alby !== undefined`

because it's a primitive value it won't cause a re-render, and most likely you need to refresh anyway if you didn't have the Alby extension before because alby wouldn't be injected

File: frontend/src/screens/wallet/index.tsx [hunk 2]
```diff
@@ -70,34 +80,36 @@ function Wallet() {
...
+                    className="w-12 h-12 rounded-xl p-1 border bg-[#FFDF6F]"
+                  />
+                  <div>
+                    <CardTitle>
+                      <div className="flex-1 leading-5 font-semibold text-xl whitespace-nowrap text-ellipsis overflow-hidden ml-4">
+                        Alby Browser Extension
+                      </div>
+                    </CardTitle>
+                    <CardDescription className="ml-4">
+                      Best to use when using your favourite Internet browser
```
Comment (rolznz) [inline frontend/src/screens/wallet/index.tsx:99]: I'm not sure how useful this description is. What do we try to convey here? but maybe this will be solved if we add the transaction list?

**Review by rolznz — APPROVED** [review]
utACK

File: frontend/src/screens/wallet/index.tsx (hunk 1 above)
Comment (reneaaron) [reply frontend/src/screens/wallet/index.tsx:30]: Good point :+1:

File: frontend/src/screens/wallet/index.tsx (hunk 2 above)
Comment (reneaaron) [reply frontend/src/screens/wallet/index.tsx:99]: I changed it to something a bit more descriptive :+1: Thanks for your feedback!
